// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

/// {@template assets_generator.assets_bell_icon_png.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/bell_icon.png)
/// {@endtemplate}

/// {@template assets_generator.assets_chat_icon_png.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/chat_icon.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_brain_png.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/images/brain.png)
/// {@endtemplate}

/// {@template assets_generator.assets_mic_icon_png.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/mic_icon.png)
/// {@endtemplate}

/// {@template assets_generator.assets_music_banner_png.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/music_banner.png)
/// {@endtemplate}

/// {@template assets_generator.assets_profile_icon_png.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/profile_icon.png)
/// {@endtemplate}

/// {@template assets_generator.assets_svg_app_icon_svg.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/svg/app_icon.svg)
/// {@endtemplate}

/// {@template assets_generator.assets_svg_drawer_icon_svg.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/svg/drawer_icon.svg)
/// {@endtemplate}

/// {@template assets_generator.assets_svg_heart_icon_svg.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/svg/heart_icon.svg)
/// {@endtemplate}

/// {@template assets_generator.assets_svg_home_icon_svg.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/svg/home_icon.svg)
/// {@endtemplate}

/// {@template assets_generator.assets_svg_icon_bg_svg.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/svg/icon_bg.svg)
/// {@endtemplate}

/// {@template assets_generator.assets_svg_mic_icon_svg.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/svg/mic_icon.svg)
/// {@endtemplate}

/// {@template assets_generator.assets_svg_play_icon_svg.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/svg/play_icon.svg)
/// {@endtemplate}

/// {@template assets_generator.assets_svg_search_icon_svg.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/svg/search_icon.svg)
/// {@endtemplate}

/// {@template assets_generator.assets_svg_user_icon_svg.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/svg/user_icon.svg)
/// {@endtemplate}

/// {@template assets_generator.assets_user_placeholder_png.preview}
/// ![](/Users/parthsakariya/Documents/Parth/arre_demo/assets/user_placeholder.png)
/// {@endtemplate}

// ignore_for_file: camel_case_types, unused_element
class _ {}