// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();

  /// {@macro assets_generator.assets_bell_icon_png.preview}
  static const String assets_bell_icon_png = 'assets/bell_icon.png';

  /// {@macro assets_generator.assets_chat_icon_png.preview}
  static const String assets_chat_icon_png = 'assets/chat_icon.png';

  /// {@macro assets_generator.assets_images_brain_png.preview}
  static const String assets_images_brain_png = 'assets/images/brain.png';

  /// {@macro assets_generator.assets_mic_icon_png.preview}
  static const String assets_mic_icon_png = 'assets/mic_icon.png';

  /// {@macro assets_generator.assets_music_banner_png.preview}
  static const String assets_music_banner_png = 'assets/music_banner.png';

  /// {@macro assets_generator.assets_profile_icon_png.preview}
  static const String assets_profile_icon_png = 'assets/profile_icon.png';

  /// {@macro assets_generator.assets_svg_app_icon_svg.preview}
  static const String assets_svg_app_icon_svg = 'assets/svg/app_icon.svg';

  /// {@macro assets_generator.assets_svg_drawer_icon_svg.preview}
  static const String assets_svg_drawer_icon_svg = 'assets/svg/drawer_icon.svg';

  /// {@macro assets_generator.assets_svg_heart_icon_svg.preview}
  static const String assets_svg_heart_icon_svg = 'assets/svg/heart_icon.svg';

  /// {@macro assets_generator.assets_svg_home_icon_svg.preview}
  static const String assets_svg_home_icon_svg = 'assets/svg/home_icon.svg';

  /// {@macro assets_generator.assets_svg_icon_bg_svg.preview}
  static const String assets_svg_icon_bg_svg = 'assets/svg/icon_bg.svg';

  /// {@macro assets_generator.assets_svg_mic_icon_svg.preview}
  static const String assets_svg_mic_icon_svg = 'assets/svg/mic_icon.svg';

  /// {@macro assets_generator.assets_svg_play_icon_svg.preview}
  static const String assets_svg_play_icon_svg = 'assets/svg/play_icon.svg';

  /// {@macro assets_generator.assets_svg_search_icon_svg.preview}
  static const String assets_svg_search_icon_svg = 'assets/svg/search_icon.svg';

  /// {@macro assets_generator.assets_svg_user_icon_svg.preview}
  static const String assets_svg_user_icon_svg = 'assets/svg/user_icon.svg';

  /// {@macro assets_generator.assets_user_placeholder_png.preview}
  static const String assets_user_placeholder_png =
      'assets/user_placeholder.png';
}
